name: Playwright Tests
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: | # Attempt to restore any older caches if possible.
    - name: Install dependencies
      run: npm ci
    - name: Build application
      run: npm run build
    - name: Lint application
      run: npm run lint
    - name: Start server
      run: npm start &
    - name: Install Playwright Browsers
      timeout-minutes: 5 # Add timeout
      run: npx playwright install --with-deps
    - name: Run Playwright tests
    - name: Run Playwright tests (sharded)
      run: npx playwright test --shard=${{ github.run_number }}/${{ matrix.shards }}
      continue-on-error: true # Ensures that the job completes even if tests fail
    - name: Check test status
      if: failure()
      run: |
        echo "Playwright tests failed. Check the report for details:"
        ls -l playwright-report || true # List report directory, ignore error if it doesn't exist
        cat playwright-report/index.html || true # Output report summary if exists
      if: failure()
      run: echo "Playwright tests failed" # Can be expanded to send notifications
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    strategy:
      fail-fast: false
      matrix:
        shards: [1, 2] # Change this value depending on the number of test files. Optimal value is ( test_files / cpu_cores ) rounded up
